(defpackage th.ad-example
  (:use #:common-lisp
        #:mu
        #:th))

(in-package :th.ad-example)

;; broadcast
(let* ((x ($variable 5))
       (y ($constant (tensor '(1 2 3))))
       (out ($broadcast x y)))
  ($gs! out (tensor '(1 2 3)))
  (prn ($gradient x))
  (prn ($gradient y)))

(let* ((x ($variable 5))
       (y ($constant '(1 2 3)))
       (out ($broadcast x y)))
  ($gs! out (tensor '(1 2 3)))
  (prn ($gradient x))
  (prn ($gradient y)))

(let* ((a ($constant '(5 5 5)))
       (c ($variable 5))
       (out ($broadcast c a)))
  ($gs! out)
  (prn out)
  (prn "3" ($gradient c)))

;; add
(let* ((a ($variable (tensor '(1 1 1))))
       (b ($variable (tensor '(1 1 1))))
       (out ($add a b)))
  ($gs! out (tensor '(1 2 3)))
  (prn ($gradient a))
  (prn ($gradient b)))

(let* ((a ($variable '(1 1 1)))
       (b ($variable '(1 1 1)))
       (out ($+ a b)))
  ($gs! out (tensor '(1 2 3)))
  (prn ($gradient a))
  (prn ($gradient b)))

;; sub
(let* ((x ($constant (tensor '(1 2 3))))
       (y ($variable (tensor '(3 2 1))))
       (out ($sub x y)))
  ($gs! out (tensor '(1 1 1)))
  (prn ($gradient x))
  (prn ($gradient y)))

(let* ((x ($constant '(1 2 3)))
       (y ($variable '(3 2 1)))
       (out ($- x y)))
  ($gs! out (tensor '(1 1 1)))
  (prn ($gradient x))
  (prn ($gradient y)))

;; dot
(let* ((x ($variable (tensor '(1 2 3))))
       (y ($constant (tensor '(1 2 3))))
       (out ($dot x y)))
  (prn out)
  (prn ($gradient x)))

;; update
(let* ((a ($constant (tensor '(1 1 1))))
       (b ($variable (tensor '(1 2 3))))
       (out ($dot a b)))
  (prn out)
  ($gd! b)
  (prn b))

(let* ((a ($constant '(1 1 1)))
       (b ($variable '(1 2 3)))
       (out ($@ a b)))
  (prn out)
  ($gd! b)
  (print b))

;; mv
(let* ((X ($constant '((1) (3))))
       (b ($variable '(10)))
       (out ($mv X b)))
  (prn out)
  (prn ($gradient b)))

(let* ((m ($variable (tensor '((2 0) (0 2)))))
       (v ($constant (tensor '(2 3))))
       (out ($mv m v)))
  ($gs! out)
  (prn (tensor '((2.0 3.0) (2.0 3.0))))
  (prn ($gradient m)))

(let* ((a ($variable '((1 1 1) (1 1 1))))
       (b ($variable '((0.1) (0.1) (0.1))))
       (out ($sigmoid ($mm a b))))
  ($gs! out)
  (prn "2.44458...")
  (prn ($gradient a)))

;; update effect for sum
(let* ((x ($variable '((1 2 3) (4 5 6) (7 8 9))))
       (y ($constant 40))
       (out ($sum x))
       (delta ($sub out y))
       (loss ($dot delta delta)))
  (prn out)
  (prn loss)
  ($gs! loss)
  (prn ($gradient x))
  ($gd! x 0.01)
  (prn x)
  (prn "decreased")
  (prn ($sum x)))

;; mean
(let* ((x ($variable '((1 2 3) (4 5 6) (7 8 9))))
       (y ($constant 6))
       (out ($mean x)))
  (prn out)
  (loop :for i :from 1 :to 50
        :for y* = ($mean x)
        :for d = ($sub y* y)
        :for l = ($dot d d)
        :do (progn
              ($gs! l)
              ($gd! x 0.9)))
  (prn x)
  (prn "closer to 6")
  (prn ($mean x)))

;; max
(let* ((x ($variable '((1 2) (3 4) (5 6))))
       (y ($constant 5))
       (out ($max x)))
  (prn out)
  (loop :for i :from 1 :to 50
        :for y* = ($max x)
        :for d = ($sub y* y)
        :for l = ($dot d d)
        :do (progn
              ($gs! l)
              ($gd! x 0.1)))
  (prn x)
  (prn "closer to 5")
  (prn ($max x)))

;; min
(let* ((x ($variable '((1 2) (3 4) (5 6))))
       (y ($constant 5))
       (out ($min x)))
  (prn out)
  (loop :for i :from 1 :to 50
        :for y* = ($min x)
        :for d = ($sub y* y)
        :for l = ($dot d d)
        :do (progn
              ($gs! l)
              ($gd! x 0.5)))
  (prn x)
  (prn "closer to 5")
  (prn ($min x)))

;; reshape
(let* ((x ($variable '((1 2) (3 4))))
       (a ($constant '(1 2 3 4)))
       (y ($constant 20))
       (out ($dot ($reshape x 1 4) a))
       (delta ($sub out y))
       (loss ($dot delta delta)))
  (prn out)
  (prn delta)
  (prn loss)
  ($gs! loss)
  (prn ($gradient x))
  (prn x)
  ($gd! x)
  (prn x)
  (prn "supposed to be decreased")
  (prn ($sub ($dot ($reshape x 1 4) a) y)))

;; with transpose
(let* ((x ($variable '((1 2) (3 4))))
       (a ($constant '(1 2 3 4)))
       (y ($constant 20))
       (out ($dot ($reshape ($transpose x) 1 4) a))
       (delta ($sub out y))
       (loss ($dot delta delta)))
  (prn out)
  (prn loss)
  ($gs! loss)
  (prn ($gradient x))
  ($gd! x)
  (prn x)
  (prn ($dot ($reshape ($transpose x) 1 4) a))
  (loop :for i :from 1 :to 10
        :for y* = ($dot ($reshape ($transpose x) 1 4) a)
        :for d = ($sub y* y)
        :for l = ($dot d d)
        :do (progn
              ($gs! l)
              ($gd! x 0.01)))
  (prn x)
  (prn ($dot ($reshape ($transpose x) 1 4) a)))

;; linear mapping
(let* ((X ($constant (tensor '((1) (3)))))
       (Y ($constant (tensor '(-10 -30))))
       (c ($variable 0))
       (b ($variable (tensor '(10)))))
  (loop :for i :from 0 :below 2000
        :do (let* ((d ($sub ($add ($mv X b) ($broadcast c Y)) Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c)
              ($gd! b)))
  (prn b))

(let* ((X ($constant '((1) (3))))
       (Y ($constant '(-10 -30)))
       (c ($variable 0))
       (b ($variable '(10))))
  (loop :for i :from 0 :below 2000
        :do (let* ((d ($- ($+ ($@ X b) ($broadcast c Y)) Y))
                   (out ($@ d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c)
              ($gd! b)))
  (prn b))

(let* ((X ($constant (-> (range 0 10)
                         ($transpose!))))
       (Y ($constant (range 0 10)))
       (c ($variable 0))
       (b ($variable (tensor '(0))))
       (a 0.001))
  (loop :for i :from 0 :below 2000
        :do (let* ((Y* ($add ($mv X b) ($broadcast c Y)))
                   (d ($sub Y* Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c a)
              ($gd! b a)))
  (prn b))

(let* ((X ($constant (-> (range 0 10)
                         ($transpose!))))
       (Y ($constant (range 0 10)))
       (c ($variable 0))
       (b ($variable (tensor '(0))))
       (a 0.001))
  (loop :for i :from 0 :below 2000
        :do (let* ((Y* ($+ ($@ X b) ($broadcast c Y)))
                   (d ($- Y* Y))
                   (out ($@ d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c a)
              ($gd! b a)))
  (prn b))

(let* ((X ($constant (-> (tensor '((1 1 2)
                                   (1 3 1)))
                         ($transpose!))))
       (Y ($constant (tensor '(1 2 3))))
       (c ($variable 0))
       (b ($variable (tensor '(1 1))))
       (a 0.05))
  (loop :for i :from 0 :below 1000
        :do (let* ((d ($sub ($add ($mv X b) ($broadcast c Y)) Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c a)
              ($gd! b a)))
  (prn b)
  (prn c))

(let* ((X ($constant (-> (tensor '((1 1 2)
                                   (1 3 1)))
                         ($transpose!))))
       (Y ($constant (tensor '(1 2 3))))
       (c ($variable 0))
       (b ($variable (tensor '(1 1))))
       (a 0.05))
  (loop :for i :from 0 :below 1000
        :do (let* ((d ($- ($+ ($@ X b) ($broadcast c Y)) Y))
                   (out ($@ d d)))
              (when (zerop (mod i 100)) (prn (list i ($data out))))
              ($gd! c a)
              ($gd! b a)))
  (prn b)
  (prn c))

;; regressions
(let* ((X ($constant (-> (tensor '(1 3))
                         ($transpose!))))
       (Y ($constant (tensor '(-10 -30))))
       (c ($variable 0))
       (b ($variable (tensor '(10))))
       (a 0.02))
  (loop :for i :from 0 :below 1000
        :do (let* ((d ($sub ($add ($mv X b) ($broadcast c Y)) Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! c a)
              ($gd! b a)))
  (prn ($add ($mv X b) ($broadcast c Y))))

(let* ((X ($constant (-> (tensor '(1 3))
                         ($transpose!))))
       (Y ($constant (tensor '(-10 -30))))
       (c ($variable 0))
       (b ($variable (tensor '(10))))
       (a 0.02))
  (loop :for i :from 0 :below 1000
        :do (let* ((d ($- ($+ ($@ X b) ($broadcast c Y)) Y))
                   (out ($@ d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! c a)
              ($gd! b a)))
  (prn ($+ ($@ X b) ($broadcast c Y))))

(let* ((X ($constant (tensor '((5 2) (-1 0) (5 2)))))
       (Y ($constant (tensor '(1 0 1))))
       (c ($variable 0))
       (b ($variable (tensor '(0 0))))
       (a 0.1))
  (loop :for i :from 0 :below 1000
        :do (let* ((Y* ($sigmoid ($add ($mv X b) ($broadcast c Y))))
                   (out ($bce Y* Y)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! c a)
              ($gd! b a)))
  (prn ($sigmoid ($add ($mv X b) ($broadcast c Y)))))

;; xor
(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 1.0))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($sigmoid ($mm X w1)))
                   (l2 ($sigmoid ($mm l1 w2)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)))
  (prn w1)
  (prn w2)
  (prn (let* ((l1 ($sigmoid ($mm X w1)))
                (l2 ($sigmoid ($mm l1 w2))))
           l2)))

(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (b1 ($variable (zeros 3)))
       (b2 ($variable (ones 1)))
       (o1 ($constant (ones 4)))
       (o2 ($constant (ones 4)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 1))
  (loop :for i :from 0 :below 1000
        :do (let* ((xw1 ($mm X w1))
                   (xwb1 ($add xw1 ($vv o1 b1)))
                   (l1 ($sigmoid xwb1))
                   (lw2 ($mm l1 w2))
                   (lwb2 ($add lw2 ($vv o2 b2)))
                   (l2 ($sigmoid lwb2))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)
              ($gd! b1 a)
              ($gd! b2 a)))
  (prn w1)
  (prn b1)
  (prn w2)
  (prn (let* ((l1 ($sigmoid ($add ($mm X w1) ($vv o1 b1))))
                (l2 ($sigmoid ($add ($mm l1 w2) ($vv o2 b2)))))
           l2)))

(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (b1 ($variable (ones 3)))
       (b2 ($variable (ones 1)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 5))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($sigmoid ($xwpb X w1 b1)))
                   (l2 ($sigmoid ($xwpb l1 w2 b2)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)
              ($gd! b1 a)
              ($gd! b2 a)))
  (prn (let* ((l1 ($sigmoid ($xwpb X w1 b1)))
              (l2 ($sigmoid ($xwpb l1 w2 b2))))
         l2)))

(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 1))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($tanh ($mm X w1)))
                   (l2 ($sigmoid ($mm l1 w2)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)))
  (prn (let* ((l1 ($tanh ($mm X w1)))
              (l2 ($sigmoid ($mm l1 w2))))
         l2)))

(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (b1 ($variable (ones 3)))
       (b2 ($variable (ones 1)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 1))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($tanh ($xwpb X w1 b1)))
                   (l2 ($sigmoid ($xwpb l1 w2 b2)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)
              ($gd! b1 a)
              ($gd! b2 a)))
  (prn (let* ((l1 ($tanh ($xwpb X w1 b1)))
              (l2 ($sigmoid ($xwpb l1 w2 b2))))
         l2)))

(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (b1 ($variable (ones 3)))
       (b2 ($variable (ones 1)))
       (o1 ($constant (ones 4)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 0.2))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($tanh ($xwpb X w1 b1 o1)))
                   (l2 ($sigmoid ($xwpb l1 w2 b2 o1)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($gd! w1 a)
              ($gd! w2 a)
              ($gd! b1 a)
              ($gd! b2 a)))
  (prn (let* ((l1 ($tanh ($xwpb X w1 b1)))
              (l2 ($sigmoid ($xwpb l1 w2 b2))))
         l2)))

;; momentum
(let* ((w1 ($variable (rndn 2 3)))
       (w2 ($variable (rndn 3 1)))
       (b1 ($variable (ones 3)))
       (b2 ($variable (ones 1)))
       (o1 ($constant (ones 4)))
       (X ($constant '((0 0) (0 1) (1 0) (1 1))))
       (Y ($constant '(0 1 1 0)))
       (a 0.2))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($tanh ($xwpb X w1 b1 o1)))
                   (l2 ($sigmoid ($xwpb l1 w2 b2 o1)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              (when (zerop (mod i 100)) (prn ($data out)))
              ($mgd! w1 a)
              ($mgd! w2 a)
              ($mgd! b1 a)
              ($mgd! b2 a)))
  (prn (let* ((l1 ($tanh ($xwpb X w1 b1)))
              (l2 ($sigmoid ($xwpb l1 w2 b2))))
         l2)))

(defun fwd (input weight) ($sigmoid! ($@ input weight)))
(defun dwb (delta output) ($* delta output ($- 1 output)))

(let* ((X (tensor '((0 0 1) (0 1 1) (1 0 1) (1 1 1))))
       (Y (tensor '((0) (1) (1) (0))))
       (w1 (rndn 3 3))
       (w2 (rndn 3 1))
       (lr 1))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 (fwd X w1))
                   (l2 (fwd l1 w2))
                   (l2d (dwb ($- l2 y) l2))
                   (l1d (dwb ($@ l2d ($transpose w2)) l1))
                   (dw2 ($@ ($transpose l1) l2d))
                   (dw1 ($@ ($transpose X) l1d)))
              ($sub! w1 ($* lr dw1))
              ($sub! w2 ($* lr dw2))))
  (prn (fwd (fwd X w1) w2)))

(let* ((w1 ($variable (rndn 3 3)))
       (w2 ($variable (rndn 3 1)))
       (X ($constant '((0 0 1) (0 1 1) (1 0 1) (1 1 1))))
       (Y ($constant '(0 1 1 0)))
       (lr 1))
  (loop :for i :from 0 :below 1000
        :do (let* ((l1 ($sigmoid ($mm X w1)))
                   (l2 ($sigmoid ($mm l1 w2)))
                   (d ($sub l2 Y))
                   (out ($dot d d)))
              ($gs! out 1)
              ($gd! w1 lr)
              ($gd! w2 lr)))
  (prn ($sigmoid ($mm ($sigmoid ($mm X w1)) w2))))
