(in-package :th.pp)

(defgeneric of-lt (n v))
(defgeneric of-le (n v))
(defgeneric of-gt (n v))
(defgeneric of-ge (n v))
(defgeneric of-it (n min max))
(defgeneric of-ie (n min max))
(defgeneric of-ot (n min max))
(defgeneric of-oe (n min max))

(defmethod of-lt ((n number) v) (< n v))
(defmethod of-le ((n number) v) (<= n v))
(defmethod of-gt ((n number) v) (> n v))
(defmethod of-ge ((n number) v) (>= n v))
(defmethod of-it ((n number) min max) (and (> n min) (< n max)))
(defmethod of-ie ((n number) min max) (and (>= n min) (<= n max)))
(defmethod of-ot ((n number) min max) (or (< n min) (> n max)))
(defmethod of-oe ((n number) min max) (or (<= n min) (>= n max)))

(defmethod of-lt ((n tensor) v) (zerop ($sum ($ge n v))))
(defmethod of-le ((n tensor) v) (zerop ($sum ($gt n v))))
(defmethod of-gt ((n tensor) v) (zerop ($sum ($le n v))))
(defmethod of-ge ((n tensor) v) (zerop ($sum ($lt n v))))
(defmethod of-it ((n tensor) min max) (and (of-gt n min) (of-lt n max)))
(defmethod of-ie ((n tensor) min max) (and (of-ge n min) (of-le n max)))
(defmethod of-ot ((n tensor) min max) (or (of-lt n min) (of-gt n max)))
(defmethod of-oe ((n tensor) min max) (or (of-le n min) (of-ge n max)))

(defun of-plusp (n) (of-gt n 0))
(defun of-minusp (n) (of-lt n 0))
(defun of-unit-interval-p (n) (of-ie n 0 1))
