(defpackage :th.ad-test
  (:use #:common-lisp
        #:mu
        #:th))

(in-package :th.ad-test)

(let* ((a ($constant (tensor '(5 5 5))))
       (c ($variable 5))
       (out ($broadcast c a))
       (gradient ($bp! out (tensor '(1 1 1)))))
  (unless ($eq ($data out) ($data a))
    (error "out should be the same one as a"))
  (unless (= 3 (-> gradient
                   ($children)
                   ($first)
                   ($gradient)))
    (error "should be 3")))

(let* ((a ($constant (tensor '(1 0 -3.21))))
       (b ($constant (tensor '(-1.3 2.8 -0.1)))))
  (unless (< (abs (- 11.3041 ($data ($dot a a)))) 0.0001)
    (error "invalid dot a and a"))
  (unless (< (abs (- -0.979 ($data ($dot a b)))) 0.01)
    (error "invalid dot a and b"))
  (unless ($eq ($data ($add a b)) (tensor '(-0.3 2.8 -3.31)))
    (error "invalid add a b"))
  (unless ($eq ($data ($sub a b)) (tensor '(2.3 -2.8 -3.11)))
    (error "invalid sub a b"))
  (unless ($eq ($data ($mul a b)) (tensor '(-1.3 0.0 0.321)))
    (error "invalid mul a b"))
  (unless ($eq ($data ($mv ($constant (tensor '((1 0 0) (0 2 0) (0 0 3)))) a))
               (tensor '(1.0 0.0 -9.63)))
    (error "invalid mm"))
  (unless ($eq ($data ($sigmoid a)) (tensor '(0.73 0.50 0.04)))
    (error "invalid sigmoid"))
  (unless ($eq ($data ($log ($constant (tensor '(0.2 0.9 3.21)))))
               (tensor '(-1.6094379124341003
                         -0.10536051565782628
                         1.1662709371419244)))
    (error "invalid log"))
  (unless (= ($data ($bce ($constant (tensor '(0.1 0.5 0.9)))
                          ($constant (tensor '(0 0 1)))))
             0.9038682400222361d0)
    (error "invalid bce")))

(let* ((m ($variable (tensor '((2 0) (0 2)))))
       (v ($constant (tensor '(2 3))))
       (out ($mv m v))
       (gradient ($bp! out (tensor '(1 1)))))
  (unless ($eq (-> gradient ($children) ($first) ($gradient))
               (tensor '((2.0 2.0) (3.0 3.0))))
    (print (-> gradient ($children) ($first) ($gradient)))
    (error "mv")))

(let* ((A (tensor '((1 1 1) (1 1 1))))
       (B (tensor '((0.1) (0.1) (0.1))))
       (delta (tensor '((1.0) (1.0))))
       (out ($sigmoid ($mm ($variable A) ($variable B))))
       (gradient ($bp! out delta)))
  (unless ($eq (-> gradient ($children) ($first) ($gradient))
               (tensor '((2.4445831169074586)
                         (2.4445831169074586))))
    (error "mm")))
